backend:
  name: github
  repo: p-goetz/netlify-cms-sandbox
  branch: main

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Page"
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
